Robots
egorzainullin/C-Year2 pull request #3
Opened 2017-12-25 13:43 UTC by egorzainullin

2017-12-26 05:06 UTC, yurii-litvinov requested changes

2017-12-26 05:06 UTC, yurii-litvinov commented on Robots/GraphWithRobotsTests/GraphWithRobotsTests.cs
> +            matrix1 = new bool[,] { { true, false, true },
Можно просто new[,], что оно bool компилятор догадается по типу поля

2017-12-26 05:06 UTC, yurii-litvinov commented on Robots/Robots/GraphWithRobots.cs
> +        public IList<int> Positions { get; private set; }
private set им не нужен, никакой содержательной логики в нём нет, а значение в своё свойство в конструкторе класс может писать и так

2017-12-26 05:06 UTC, yurii-litvinov commented on Robots/Robots/GraphWithRobots.cs
> +            }
Оно и так будет false, при выделении памяти в куче дотнет-машина заполняет её нулями

2017-12-26 05:06 UTC, yurii-litvinov commented on Robots/Robots/GraphWithRobots.cs
> +                        resultList = ListMerging.MergeWithoutRepeating(resultList, temp);
Потому что на самом деле соседи --- это ISet, и тогда можно было бы воспользоваться готовой реализацией объединения множеств, а не делать свой велосипед :)

2017-12-26 15:21 UTC, egorzainullin commented on Robots/Robots/GraphWithRobots.cs
> +                        resultList = ListMerging.MergeWithoutRepeating(resultList, temp);
Это переделать или нет?

2017-12-26 15:21 UTC, yurii-litvinov commented on Robots/Robots/GraphWithRobots.cs
> +                        resultList = ListMerging.MergeWithoutRepeating(resultList, temp);
Переделать

2017-12-27 04:53 UTC, yurii-litvinov approved these changes
👍

2017-12-27 04:53 UTC, yurii-litvinov commented on Robots/Robots/GraphWithRobots.cs
> +        private SortedSet<int> GetNeighbors(int node)
Оно обязательно должно быть Sorted?

2017-12-27 07:54 UTC, merged